# Generated by Django 5.0.7 on 2024-09-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['-create_at']},
        ),
    ]
